### ISSUE TITLE
vl5x.js issue

### ISSUE THREAD

**Issue by ghyn** [sixs/wenshu_spider#6]
got error as below:

Traceback (most recent call last):
  File "C:/Users/gangh/OneDrive/Documents/Python/wenshu_spider/court.py", line 20, in <module>
    js = fp.read()
  File "C:\Users\gangh\Anaconda3\envs\web\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 18: character maps to <undefined>

Please help. Thanks!

**Comment by Newpeee** [comment]
同问同问，也是这里有问题，没法实现DocID的解密，有劳作者解决下

**Comment by sixs** [comment]
我这边运行正常，能截下图么

**Comment by Newpeee** [comment]
我把你解docid的方法单独抠出来运行，复制了某一次搜索返回的列表页中RunEval值和某一个DocID，无法解密，报错
![12](https://user-images.githubusercontent.com/40019316/45141769-608ab700-b1e9-11e8-8251-ce1f37a1baaa.png)
![23](https://user-images.githubusercontent.com/40019316/45141774-654f6b00-b1e9-11e8-90ae-1b2f8dce1c13.png)
然后运行你的程序也报类似的错误

![45](https://user-images.githubusercontent.com/40019316/45142022-0807e980-b1ea-11e8-9ac0-71862189aaf0.png)
@sixs

**Comment by sixs** [comment]
![default](https://user-images.githubusercontent.com/18512120/45143755-b1e97500-b1ee-11e8-951a-dfadec3448b9.JPG)
![1](https://user-images.githubusercontent.com/18512120/45143757-b2820b80-b1ee-11e8-8e3e-12ff0917f292.JPG)
单独提取出来也是没问题的，你先确认下是个别解密有问题还是全部有问题，若是前者，在decrypt_id函数中加个异常捕获然后错误重新获取RunEval解决；若是后者，可能为环境问题，报一下你的电脑系统信息和python版本信息。

**Comment by Newpeee** [comment]
老哥解决了 我这边缺了js环境 谢谢你，然后在readme里面能大概说下破解docid的过程和相应docid.js如何去编写的过程吗？想跟您学习下

**Comment by Newpeee** [comment]
@sixs

**Comment by ghyn** [comment]
@Newpeee 朋友，能解释下怎么搞定这个JS环境么？谢谢。

**Comment by Newpeee** [comment]
windows环境，安装nood.js就好 @ghyn

**Comment by Newpeee** [comment]
对 打错了 node.js @ghyn

**Comment by g2dog** [comment]
@Newpeee   我装了node.js 也不行  需要配置什么吗？

**Comment by lifecrazy** [comment]
想问一下，我也安装了node.js还是不行，需要配置什么吗？谢谢@Newpee

**Comment by g2dog** [comment]
@lifecrazy 安装完Node.js 跟换cnpm的镜像就好了（执行下面这条语句）
npm install -g cnpm --registry=https://registry.npm.taobao.org

**Comment by ghyn** [comment]
@sixs 求助大神。文书网现在好像一爬就要验证码，而且你的代码里检查验证码的部分过不了。。。

**Comment by SmokedInk** [comment]
@ghyn 你的这个问题解决了吗，我也是这样
